#pragma once

#include "Engine/Framework/FrameworkTestCase.h"

unique_pointer<FrameworkTestCase> createFrameworkEntityAddRemoveTestCase();
unique_pointer<FrameworkTestCase> createFrameworkEntityUpdateTestCase();
unique_pointer<FrameworkTestCase> createFrameworkEntityBridgeTestCase();
unique_pointer<FrameworkTestCase> createFrameworkEntityBridgeSyncTestCase();
unique_pointer<FrameworkTestCase> createFrameworkBridgeLifecycleTestCase();
unique_pointer<FrameworkTestCase> createFrameworkObjMeshLoaderTestCase();
unique_pointer<FrameworkTestCase> createFrameworkRootSignatureLifecycleTestCase();
unique_pointer<FrameworkTestCase> createFrameworkPipelineStateLifecycleTestCase();
unique_pointer<FrameworkTestCase> createFrameworkShaderPackageTestCase();
unique_pointer<FrameworkTestCase> createFrameworkWorldSerializationTestCase();
